### ISSUE TITLE
Thanks - One question

### ISSUE THREAD

**Issue by mouazzz** [kernworks/OpenVBX-Plugin-Recording#6]
Hello,

Thanks for a great plugin. It just works perfectly. 

I am just wondering, is there anyway to record outbound calls? I use an iPhone app to call from my Twilio number, but I wish also to record this conversation. The plugin works perfectly for inbound calls. Do you think adding outbound call recording is something you are considering in a coming release?

Thanks again

**Comment by kernworks** [comment]
I am still in the process of verifying the visibility of outbound call recordings on the Recorded Calls page.

The client you use to make the call (iPhone app in your case) has to specifically set the recording flag when you make a call in order for Twilio to know you want it recorded. This plugin cannot control that part of it.

**Comment by mouazzz** [comment]
Thank you so much for taking the time to reply. I agree, the second point is crucial. Unfortunately, on iOS App store, there are only two Twilio/OpenVBX apps; one is by Twilio which is outdated for few years, and the other one is called (CallMart) and works perfectly. So, let's see how to get outbound call recording flagged in that app. Will write to the developer. 

Thanks again,

**Comment by kernworks** [comment]
Feel free to open this back up if you have more questions on this topic.
